### ISSUE TITLE
Add more option for templating.

### ISSUE THREAD

**Issue by cwps** [muckypuddle/joomla-tags-selected#2]
This isn't an issue, just an enhancement question.

Are you planing to add more option to user in this module? Like to show Title or not, or show the publish date or create date, etc.?

**Comment by paul-muckypuddle** [comment]
If you have a specific list of options you have in mind post them here and I can look into adding them - shouldn't be too much work.

**Comment by cwps** [comment]
I think these options will suffice:
- Show Title
- Show Intro Text and option to limit the total character to show
- Show Publish/Create/Modify Date
- Show Author

But a more advanced templating can be achieved if we show the article image.
Give them option to get image whether from intro image/full article image or taken from the first image in intro text or full article.
An example from this maybe creating a Slider/Slideshow or something like front-page news articles.

**Comment by paul-muckypuddle** [comment]
Title, dates and author are all simple enough. Images - these only apply to articles, whereas tags can be added to anything - so the content type matters. If the user picks content type 'weblinks' then a 'show article image' option doesn't make sense.

**Comment by cwps** [comment]
Yes you are right and Thank you for your attention for this enhancement question. Can't wait for you to implement them.

**Comment by paul-muckypuddle** [comment]
@cwps - just reviewing this now. I've now included the option to show a date (publish / create or modify) and show the author. There's also another layout, 'readmore', which will obey any 'read more' bars put in your articles so it only shows the part before the read more (most editors have a button for this).

**Comment by Bugsbane** [comment]
> There's also another layout, 'readmore', which will obey any 'read more' bars put in your articles so it only shows the part before the read more

Thank you! I use "Read more" extensively on my site! (Usually a large article image, then a short introductory paragraph and a read more button is how I like most of my lists).

It really surprises me that something like this extension wasn't added in Joomla 3.2 when tags were. If this follows Joomla's code style properly, I'd seriously consider submitting it to Joomla core for inclusion.
