### ISSUE TITLE
Fatal error if Include Children set to Yes.

### ISSUE THREAD

**Issue by cwps** [muckypuddle/joomla-tags-selected#3]
It giving this error message:
`Fatal error: Call to a member function isLeaf() on a non-object in \htdocs\libraries\cms\helper\tags.php on line 647`

My system: Joomla 3.3.6; PHP 5.3.10

**Comment by paul-muckypuddle** [comment]
Thanks for the bug report @cwps - could you give the new zip archive a shot?

**Comment by paul-muckypuddle** [comment]
Actually, ignore that - seems to be an issue with the Joomla TagsHelper class. I've submitted a pull request to fix the issue at the joomla-cms end - https://github.com/joomla/joomla-cms/pull/5369
