### ISSUE TITLE
Content Type Heading

### ISSUE THREAD

**Issue by emmarichardson** [muckypuddle/joomla-tags-selected#5]
Firstly - thank you so much for taking this and enhancing with content type - after spending several days trying to find a simple way to show contacts for a particular tag, I was about to tear my hair out until I came across this!!

It would nice to have the option to have the type of tag as a heading even if that is the only kind you are linking to.  I am using this within an article and love the nice way the links display but would appreciate having a Contacts Heading above the list..not that I can't put one in myself but with a dynamically changing list, it would obviously be better within the results.  Or a nice accordion style list maybe...?

Also, any chance of getting K2 articles included?

**Comment by paul-muckypuddle** [comment]
Hi - this should now be in as of v.1.1 - fancy downloading and giving it a try?

If K2 exposes itself as a 'content type' then the module should already acknowledge it in the 'Content Items' list. If not, would recommend noising up the K2 team and seeing if they can make their their content 'content-type' compatible (AFAIK this involves a bit of work, but isn't a huge architectural PITA).

Cheers!

**Comment by emmarichardson** [comment]
Awesome.  This is what I have figured out/noticed.  K2 uses its own tag system which is very annoying so looking at alternatives there!

On the layout, if there are multiple types selected, you do not get the Content Type heading (Contact/Article) unless you select the Show Content Types option and then you get a large heading that says "Content Type" and the actual content types are in small text below.

If you only have one type selected, even with the Content Type Heading set to No, you get the heading by content type (Contact, e.g.).  This is the behavior I was looking for but curious that it happens regardless of the setting.

Thanks for doing this!!
Emma

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037
Desktop Video: https://ecboces.zoom.us/j/7196503037https://ecboces.zoom.us/my/emmar

On March 3, 2015 at 5:04:19 AM, Paul Holmes (notifications@github.commailto:notifications@github.com) wrote:

Hi - this should now be in as of v.1.1 - fancy downloading and giving it a try?

If K2 exposes itself as a 'content type' then the module should already acknowledge it in the 'Content Items' list. If not, would recommend noising up the K2 team and seeing if they can make their their content 'content-type' compatible (AFAIK this involves a bit of work, but isn't a huge architectural PITA).

Cheers!

**Comment by paul-muckypuddle** [comment]
Aye, bit of a pain that - that said, K2 did have tagging eons before Joomla so can't fault em too much.

Re: layout - there are 3 possible combinations that I've seen in testing:
1. Show Content Types set to 'False' = no content type info shows.
2. Show Content Types set to 'True', and 1 content type selected  = content type appears as header above items
3. Show Content Types set to 'True', and 2 or more content types selected = 'Content Type' header appears with list of content types shown underneath

You said that:

_If you only have one type selected, even with the Content Type Heading set to No, you get the heading by content type (Contact, e.g.)_

I can't replicate this behaviour?

**Comment by emmarichardson** [comment]
Maybe I have a caching issue going on…I think it is working correctly maybe.  I actually have some strange variations - some with show content on with no content heading, some with show content off with content heading!!!  This has been an ongoing issue with this site and strangely enough I have caching disabled at the site level  - guess I need to go and revisit that problem!!  Probably something to do with the Moodle site I have running on this server - I think it has opcache enabled and I bet that is maybe affecting the Joomla site too.

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037
Desktop Video: https://ecboces.zoom.us/j/7196503037https://ecboces.zoom.us/my/emmar

On March 3, 2015 at 9:02:53 AM, Paul Holmes (notifications@github.commailto:notifications@github.com) wrote:

Aye, bit of a pain that - that said, K2 did have tagging eons before Joomla so can't fault em too much.

Re: layout - there are 3 possible combinations that I've seen in testing:
1.  Show Content Types set to 'False' = no content type info shows.
2.  Show Content Types set to 'True', and 1 content type selected = content type appears as header above items
3.  Show Content Types set to 'True', and 2 or more content types selected = 'Content Type' header appears with list of content types shown underneath

You said that:

If you only have one type selected, even with the Content Type Heading set to No, you get the heading by content type (Contact, e.g.)

I can't replicate this behaviour?

**Comment by paul-muckypuddle** [comment]
Ah Joomla caching. The optimisation black box.

I haven't the time right now to set up a fresh vagrant box and do cache / no cache testing, but will try to do so in the near future. Hopefully module is useful in its current state though!

**Comment by emmarichardson** [comment]
It is - thank you so much.  This was my savior after two very frustrating days - thought I was going to have to go to coding school just to fix at one point!!  Thanks again!!

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037
Desktop Video: https://ecboces.zoom.us/j/7196503037https://ecboces.zoom.us/my/emmar

On March 3, 2015 at 9:17:28 AM, Paul Holmes (notifications@github.commailto:notifications@github.com) wrote:

Ah Joomla caching. The optimisation black box.

I haven't the time right now to set up a fresh vagrant box and do cache / no cache testing, but will try to do so in the near future. Hopefully module is useful in its current state though!

**Comment by paul-muckypuddle** [comment]
Not a problem - closing this one down.
